### PR TITLE
don't require httpkit and jetty

### PR DESCRIPTION
**Pull request by timothypratley**
Even as an unloaded namespace, httpkit and jetty may be discovered by code reload tools... so don't do it that way.

### CODE REVIEW

**Comment by timothypratley** [comment]
@kpassapk I think this will solve the namespace loading, what do you think?

**Comment by kpassapk** [comment]
> @kpassapk I think this will solve the namespace loading, what do you think?

I think so, let me check it out!

**Comment by kpassapk** [comment]
I was able to reload it, with the small change in the PR above :)

**Comment by timothypratley** [comment]
great, thank you!!!

**Pull request merged**
